# Generated by Django 4.1 on 2022-10-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('eng', 'Eng'), ('ua', 'Ua'), ('ru', 'Ru')], db_index=True, max_length=8, verbose_name='Word language'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=32, verbose_name='Word'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.CheckConstraint(check=models.Q(('language__in', ['eng', 'ua', 'ru'])), name='check_word_language_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word', 'language'), name='word_with_its_language_is_unique'),
        ),
    ]
